version: '3.9'

services:
  db:
    image: mysql:8.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "4306:3306"
    volumes:
      - ./mysql_conf.d:/etc/mysql/conf.d
      - ./tmp/mysql/volumes:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  web:
    build: .
    command: >
      bash -c "rm -rf tmp/pids/server.pid &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app/:cached
    environment:
      DB_HOST: db
      RAILS_ENV: development
      REDIS: 'redis://redis:6379'
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
  redis:
    image: redis:6.2.1
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    depends_on:
      - db

volumes:
  redis-data:
    driver: local

